### ISSUE TITLE
Book 3.8.3: Naming of `onb::local()`

### ISSUE THREAD

**Issue by Panjaksli** [RayTracing/raytracing.github.io#1088]
Hello, sorry if my question is dumb.
But why is this method called "local",
when we are actually transforming from local space to world space ?

**Comment by hollasch** [comment]
"Local" is relative. I can't speak for Peter's original intent, but I would call this a model-to-local coordinate transform. But every space's "world" coordinates is some other space's "model" coordinates, because transforms concatenate. I definitely wouldn't call this a transform to "world space", as we may have many other transforms ahead of us. For example, a given quad has modeling coordinates, but then may be transformed to assemble a box, which is then transformed into the Cornell scene, which is then inverse-transformed by the camera (or not, depending on how you model viewing transforms).

All that said, I do agree that `local()` doesn't really provide much value as a name. I'll see if I can come up with a better one.

**Comment by hollasch** [comment]
After thinking about this a bit more, and given the overall generality of the orthonormal basis class, I don't think this can be made any more specific than `transform()`. It transforms points from the orthonormal basic coordinate system into the coordinates of the basis vectors themselves. I really don't like calling these "world" coordinates, but also don't want to name them anything else, as that would be like saying that a `vec3` is necessarily in some particularly named coordinate system. I think `transform()` is as good as it gets.
