### ISSUE TITLE
[Book 1] Conceptual improvement in the algorithm description on subsection 4.2 - Sending Rays Into the Scene

### ISSUE THREAD

**Issue by carvalhais** [RayTracing/raytracing.github.io#1248]
Hi, it is a nice coincidence that I came across this book series in just the right time to be able to contribute to them a little bit. I apologize in advance if I make any nonsensical suggestion, but I have no experience at all with any computer graphics, and reading these books is more of a personal project to me.

Regarding the conceptual explanation of a ray tracer in subsection 4.2, the text reads as the following around the 5<sup>th</sup> paragraph and beyond:

> The image's aspect ratio can be determined from the ratio of its height to its width. However, since we have a given aspect ratio in mind, it's easier to **set the image's width** and the aspect ratio, and then using this to calculate for its height. This way, we can scale up or down the image by changing the image width, and it won't throw off our desired aspect ratio.
> [...]
> To start things off, **we'll choose an arbitrary viewport height of 2.0**, and scale the viewport width to give us the desired aspect ratio. Here's a snippet of what this code will look like:

I understand that using a single dimension and a given aspect ration works both ways, no matter what was the chosen dimension (height or width). But the text starts with a discussion in which the author states his preference for setting the width and deducing the height from that.

Indeed that's what it's done for the image pixel size, however, when the text talks proceed to talk about the viewport, the chosen dimension is not the width, but the height. It gets a little confusing for complete newcomers. The way I see it, it looks like it make no difference, but then, that's not completely clear from the text. Maybe, just for consistency, it would make more sense to also set the width of the viewport, instead of the height.

I'm willing to fix that, both on the text and on the code, if this issue is accepted.

**Comment by carvalhais** [comment]
Also, the text mentions just before this:
> To start things off, **we'll choose an arbitrary viewport height of 2.0**, and scale the viewport width to give us the desired aspect ratio.

The text clearly mention that the chosen dimension is arbitrary, but then, why not 1.0, which would make it more "normalized"? Maybe there could be a mention that this number could be any other else, and play no important role in the algorithm mechanics. Or if it really does make a difference, mention that for the moment being this number looks arbitrary, but it was chosen for reasons that would become clear later in the text.

**Comment by carvalhais** [comment]
I kept reading the book and arrived at section 7 - Moving Camera Code Into Its Own Class. If this issue is going to be considered to be implemented, the code on this section should reflect those changes as well, specially in the following snippet of Listing 34:
```c++
// Determine viewport dimensions.
auto focal_length = 1.0;
auto viewport_height = 2.0;
auto viewport_width = viewport_height * (static_cast<double>(image_width)/image_height);
```

**Comment by hollasch** [comment]
I think we'll keep things the way they are. This has been unchanged since Peter first published the books, and I always found that it matched how I thought about things as well as how this is often presented elsewhere.

Generally, film images are wider than they are high (TikTok and phone videos notwithstanding). I find that thinking about the width is useful when trying to nail down the maximum file/image size or the pixel resolution I need for either quality or performance reasons.

When _composing_ a shot, I find that it's typical to think in terms of vertical angle — this is how film shots are typically discussed ("close-up" vs "long shot" vs "full" vs "Cowboy/American" and so on), where the aspect ratio (3:4, 16:9, Panavision, etc) is a secondary consideration.

Regarding the nominal viewport height of 2.0, that's because when working out the resulting dimensions, we use the half-angle for our trigonometry, as we need a right triangle. Thus, a total height of 2.0 gives us a working half-height of 1.0 from image center to top or bottom, and we can then solve for distance ($= \tan^{-1}(h)$, where h is the half-angle.

But as you've said, these are merely arbitrary preferences, so I'd encourage you to implement your code as you see fit and which matches your own ways of thinking about the relationship between the rendered image, the geometric viewport construct, and the camera.
