### ISSUE TITLE
Sanity pass for math.

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#13]
- For block equations, use `\frac{}{}` instead of `/`.
- Math functions should get backslashes, as in `\sin`, `\cos`, `\arccos`.
- Use `\sqrt{}` instead of `sqrt()`.
- Cuddle inline `$` delimiters (that is, no spaces between them and the equation).
- Block equations should be indented two spaces. Separate `$$` delimiters from equation with a space.

- [x] In One Weekend
  * [x] chapter 1
  * [x] chapter 2
  * [x] chapter 3
  * [x] chapter 4
  * [x] chapter 5
  * [x] chapter 6
  * [x] chapter 7
  * [x] chapter 8
  * [x] chapter 9
  * [x] chapter 10
  * [x] chapter 11
  * [x] chapter 12
- [x] The Next Week
  * [x] chapter 1
  * [x] chapter 2
  * [x] chapter 3
  * [x] chapter 4
  * [x] chapter 5
  * [x] chapter 6
  * [x] chapter 7
  * [x] chapter 8
  * [x] chapter 9
- [x] The Rest Of Your Life
  * [x] chapter 1
  * [x] chapter 2
  * [x] chapter 3
  * [x] chapter 4
  * [x] chapter 5
  * [x] chapter 6
  * [x] chapter 7
  * [x] chapter 8
  * [x] chapter 9

**Comment by trevordblack** [comment]
In the multiplication of a constant with a vector, do we want to standardize to `*` or `\cdot`

My preference is `\cdot`

**Comment by trevordblack** [comment]
Chapter 4, InOneWeekend, there are many instances of calling `dot` within math blocks.
I gather two things from this.
1. It might be prudent to replace the `dot` with `cdot`
2. We should remove operators for the multiplication between a scalar and a vector. e.g. 
$p(t) = A + tB$ rather than $p(t) = A + t \cdot B$ or $p(t) = A +t * B$

I'm not married to any of the above, but we should fix the mathematical notion.

**Comment by hollasch** [comment]
I don't mind `dot(V0,V1)`, but in general agree that I like to see `V0 \cdot V1`.

I also agree with your point 2 above.

We should never use `*` in the math markup to indicate multiplication.

**Comment by hollasch** [comment]
Out for review: #239

**Comment by hollasch** [comment]
Resolved in #239
