### ISSUE TITLE
[Book 3] Listing 5: Update Main to use case 7: cornell_box()

### ISSUE THREAD

**Issue by rupsis** [RayTracing/raytracing.github.io#1372]
Listing 5 sets up the Cornell boxes again, instead could we just switch back to using `cornell_box()` scene we set up back in book 2? 

Suggestion: 

<img width="724" alt="image" src="https://github.com/RayTracing/raytracing.github.io/assets/9646385/bc97279e-d92d-45db-aaec-a3177219846f">

Happy to make the change.

**Comment by hollasch** [comment]
I took a look at book 3 again, and I think we'll keep things the way they are. The final form at book 2 is a nice snapshot point in the material, and the book three changes to camera, hittables, materials, some geometries and other files mean that the reader would have to update all of the other scenes as well in order to be compatible — much more work than should be needed to just explore the book 3 concepts. Instead, just grabbing the single Cornell scene and then repeatedly modifying it as the book progresses is much simpler.

**Comment by cccccz** [comment]
@hollasch  
![image](https://github.com/RayTracing/raytracing.github.io/assets/60713799/a3180d66-d7f3-4726-b3f0-9cd8f35d7150)
'lights' is not defined yet

**Comment by cccccz** [comment]
also, the render function does not take 2 arguments yet?

**Comment by hollasch** [comment]
@cccccz — This issue is a suggestion about re-using the main program structure from book 2.

**Comment by hollasch** [comment]
Ah, I see now what @cccccz was talking about. This should be a separate issue.

**Comment by hollasch** [comment]
Forked to #1389.
