### ISSUE TITLE
[Book 2] 4.3 Code Listing 27 is inconsistant with Image 3.

### ISSUE THREAD

**Issue by cccccz** [RayTracing/raytracing.github.io#1374]
![image](https://github.com/RayTracing/raytracing.github.io/assets/60713799/0b651b69-e70f-4291-b65d-dd66e8156681)
![image](https://github.com/RayTracing/raytracing.github.io/assets/60713799/f511e292-854d-4c5b-a9d3-4d749c1e33f1)

Image 3 is the ouput of checker_texture with _scale = 0.32 instead of 0.8.

**Comment by rupsis** [comment]
Just to clarify, with the values listed in the book we get this results?

![image](https://github.com/RayTracing/raytracing.github.io/assets/9646385/a2afc795-a895-4492-b216-65904708319f)

considering 
> ... checker_texture is a spatial texture, we're really looking at the surface of the sphere cutting through the three-dimensional checker space

I think it would make sense to decrease the scale to better illustrate the point (rather than having a larger checker pattern)

**Comment by cccccz** [comment]
Yes, this is the result generated by the values listed and yes the smaller scale shows the artifact very well

**Comment by rupsis** [comment]
Fixed by https://github.com/RayTracing/raytracing.github.io/pull/1376
