### ISSUE TITLE
Sanity pass for code blocks.

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#14]
- [x] In One Weekend
  * [x] chapter 1
  * [x] chapter 2
  * [x] chapter 3
  * [x] chapter 4
  * [x] chapter 5
  * [x] chapter 6
  * [x] chapter 7
  * [x] chapter 8
  * [x] chapter 9
  * [x] chapter 10
  * [x] chapter 11
  * [x] chapter 12
- [x] The Next Week
  * [x] chapter 1
  * [x] chapter 2
  * [x] chapter 3
  * [x] chapter 4
  * [x] chapter 5
  * [x] chapter 6
  * [x] chapter 7
  * [x] chapter 8
  * [x] chapter 9
- [x] The Rest Of Your Life
  * [x] chapter 1
  * [x] chapter 2
  * [x] chapter 3
  * [x] chapter 4
  * [x] chapter 5
  * [x] chapter 6
  * [x] chapter 7
  * [x] chapter 8
  * [x] chapter 9

**Comment by trevordblack** [comment]
For instances of "float" and "double" and other types in the text, do we want them to be inlined, i.e.
`float`s and `double`s.

**Comment by hollasch** [comment]
I tend to use “single precision” and “double precision”, or “32-bit floats” and “64-bit floats” in prose unless I'm talking specifically about the types. If the types are important, then yeah, generally I try to mark them up as code: `float`/`double`. I'm not super strict on this, as sometimes my prose looks like a clown car of type changes, so sometimes I'll drop the inline code style just so the text reads easier (not usually).

So generally, use code styling, but with an escape hatch when you need it.

**Comment by lorihollasch** [comment]
General: should be hittable, not hitable

Book 1:
Ch 2
•	“top part of my vec3 class”:
o	Reorder include files to match src conventions
•	“lots of vector operations”:
o	dot: unclear (spaces needed?)
o	function signatures: inconsistent spacing, eg: ){ versus ) {
o	two spaces after e[x] in some methods
o	order methods consistently as + - * /
o	unbold unit_vector
•	“change our main”:
o	Reorder include files to match src conventions
o	Put spaces

Ch 3
•	“add antialiasing later”:
o	Reorder include files to match src conventions
o	Remove *world and depth parameters from color

Ch 5
•	“motion blur at some point”:
o	Put hit_record and { on same line
o	Make spacing in 2 temp calculations the same
•	“And a list of objects”:
o	Remove space between signature and hit_record_temp_rec
•	“And the new main”:
o	Reorder include files to match src conventions


Ch 6
•	“camera from before”:
o	Add #include “random.h”
•	“Main is also changed”:
o	Make spacing in s’s for loop consistent with i and j (int s = 0)


Ch 7
•	“is perfect for that”:
o	Remove depth parameter from color

Ch 8
•	“in the hitable class below”:
o	Put hit_record and { on same line
•	“below marked with”:
o	Make spacing in 2 temp calculations the same
•	“For Lambertian materials”:
o	Put const and { on same line
o	Remove blank space above vec3 albedo
•	“The metal material”:
o	Put const and { on same line
•	“And add some metal”:
o	List[0] Lambertian vec3 constants are different from Pete’s
o	Make spacing in s’s for loop consistent with I and j (int s = 0)
o	Add space between world, and 0   <- do elsewhere too?
•	“sphere which yields”:
o	Put const and { on same line

Ch 9
•	“And the dielectric material”:
o	Put const and { on same line
o	Add curly braces back to if (refract) statement
•	“If we try that out”:
o	Remove 0.0 parameter from metal
•	“This yields our full glass”:
o	Put const and { on same line

Ch 10
•	“with crazy camera angles”:
o	Change lookatfrom to be lookfrom

Ch 11
•	“rather than from a point”:
o	Put const and { on same line

**Comment by lorihollasch** [comment]
Book 2:
Ch 1
•	“rays over a time period”:
o	Camera’s parameters layout differs from Book 1. Here there is one parameter per line versus several per line in Book 1
•	“aperture open close”:
o	Add space between time0 and time1

Ch 2
•	“Here is such a class”:
o	One space instead of two between class and method?
•	“will get optimized later”:
o	Add curly braces for conditions in axis if statement (for consistency)?
o	Add space between time0,time1 (2 instances)

Ch 3
•	“any color a texture”:
o	constant_texture: change open brace to open curly
o	books haven’t had spaces between {} in empty constructors. Remove space(s) between {  } (2 instances)
•	“with a texture pointer”:
o	Change “const (“ to “const {“
•	“a 3D checker pattern”:
o	Remove space(s) between { } (2 instances)
•	“If we add a new scene”:
o	List[0] and list[1] both missing );

Ch 4
•	“And we can use that one some spheres”:
o	Fix the above sentence (eg: “We can use that texture on some spheres”)
o	Change “() (“ to “() {“
•	“we can linearly interpolate”:
o	Change Z to 2
o	Remove ; from end of pexm_z calculation
•	“The Perlin class is now”:
o	Remove ; from end of pexm_z calculation
•	“giving a marble-like effect”:
o	Change “) ;” to “);”


Ch 6 Rectangles and Lights
•	“It’s very simple”:
o	Remove double spacing from “material  {“
•	“The actual xy_rect class”:
o	Remove double spacing from “hitable  {“
•	“This is yz and xz”
o	Change to “xz and yz” to align with code for better readability
o	Remove double spacing from “hitable  {“
•	“Let’s make the 5 walls”:
o	Change hitable array size to 5? (was 6 in Pete’s code; changed to 8 in new code)


Ch 7 Instances
•	“And the changes to Cornell is”:
o	^should be “changes are” or “change is”
o	Remove extraneous comma in second translate

Ch 8 Volumes
•	“And the changes to Cornell is”:
o	Remove blank line before phase function calculation
•	“And the hit function is”:
o	Be consistent with short if statements. Some are on one line, some are on two lines.

Ch 9 A Scene Testing All New Features
•	“design decision”:
o	*light calculation: remove space between “) )”
o	new sphere: add space between 400,200 and between 220,280
o	sphere in for loop has code line that is long enough to require scrolling
o	new bvh_node: add space between boxlist2,ns

**Comment by lorihollasch** [comment]
Book 3:
Ch 2 (Monte Carlo)
•	“centered at the origin”:
o	Reorder include files to match src conventions
o	Loop conditional should be i < N
•	“a running estimate”:
o	Reorder include files to match src conventions
•	“try it both ways”:
o	Reorder include files to match src conventions

Ch 3 (1D MC Integration)
•	“In fact it is exactly”:
o	Reorder include files to match src conventions
•	“and the code is”:
o	Reorder include files to match src conventions
•	“1 sample we get”:
o	Reorder include files to match src conventions

Ch 6 (Importance Sampling Materials):
•	“generates the model”:
o	Remove flip_normals from 3rd list item
o	Make lookfrom and lookat spacing consistent
•	“color function gets”:
o	Change hrec to rec

Ch 7 (Generating Random Directions)
•	“We can output”:
o	z calculation is different – is that an error or deliberate?

Ch 8 (Ortho-normal Bases)
•	“use that axis”:
o	Original book had pseudocode; new book has code block, but code isn’t correct
•	“using this to get”:
o	Remove extra space in direction calculation “) )”

Ch 9 (Sampling Lights Directly)
•	“see the highlighted region”
o	Add highlighted region

Ch 10 (Mixture Densities)
•	“with the main changes highlighted”
o	Add highlighted region
•	“And then change color”
o	Add light_shape  to parameter list (see color code later in chapter)
o	Add open curly to “if (depth)” statement 
o	Add highlighted region
•	“plugging it into color”
o	Add highlighted region
o	Add open curly to “if (depth)” statement 

Ch 12 (Cleaning Up pdf Management)
•	“And color() changes are small”
o	Add highlighted region
•	“Metal is easy to fix”
o	Add highlighted region
•	“an implicitly sampled ray”
o	Add highlighted region
•	“We also need to change the block”
o	Add highlighted region
•	“We assemble a list to pass in to color”
o	Did you mean to add all the extra code beyond hlist?
