### ISSUE TITLE
Fix float/double mismatches in source

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#150]
Lots of places where we're using `double` constants for use in `float` calculations, mixing up our widths when passing parameters, and such. We need to ensure that our code compiles without any warnings about mixing precision.

Ideally, it would be good to determine what the impact of `float` vs. `double`. Personally, I prefer double precision, as it's the native precision for math, and C++ constants, and is frequently faster on platforms that perform intrinsic computation in double-precision (and thus induce a performance hit when transforming from and to single-precision.

**Comment by vchizhov** [comment]
I am for using `float` rather than double. The main argument towards using `double` that I managed to gather from here was self  intersection.
However self-intersection occurs even with double precision. And thus should be handled in a different manner, see #137.
On the other hand using `float` allows for a straightforward extension of the code through SIMD, as well as a minor scalar code speed up.

**Comment by hollasch** [comment]
No, see my comment just above yours. Self intersection is not one of the arguments. Instead,
- `double` is frequently faster, since it can avoid conversion overhead. This is not an argument in favor, however, since ultimate performance is *not* a goal of this book.
- Most math libraries are double-precision in arguments and return value.
- Floating point literals are double-precision.

**Comment by vchizhov** [comment]
As far as the comment above mine goes, `double` vs `float` affects self intersection. It is not so much about whether it's 0.1 or 0.01 on the inside, but rather whether it ends up on the inside in the first place due to round-off error.

What conversion are we talking about? And why would `double` computations be faster? This is untrue for many machines, compilers, and compilation options. And even less true for SIMD.


The math libraries that I know of usually provide both single and double precision versions of the functions, notably so does stl.


`1.0f` is a floating-point literal. The `f` is a type specifier. So I am unsure whether the argument is that `f` is undesirable?

**Comment by hollasch** [comment]
See timing results above. This is not conclusive, but generally true that `float` can induce conversion costs to and from double (or higher) internal precision for computation. It doesn't matter, though, since the difference is tiny and irrelevant for our purposes. SIMD is a non-issue — it is outside of the scope of this book, and as I wrote above, high performance is not a goal.

The code should be most broadly useful, and I know of no platforms that provide only single-precision math libraries, while I know some that provide only double.

Regarding constants, yes, I was talking about the C-centric annoyance of having to suffix all numbers with `f`, both internal and imported. `double` can accept both single and double-precision values, `float` will give you warnings.

Readers are _strongly_ encouraged to write the raytracing code themselves. The code included in the book is for illustration, and meant to be broadly understood by programmers regardless of their preferred languages. Using `double` is a tiny improvement in that regard.

**Comment by vchizhov** [comment]
I thought that the benchmark conclusion was that the "speed up" was due to noise. One also doesn't need to convert between float and double if they keep computations in float.

Using double and the code being broadly useful clashes with SIMD and GPU ports, while allowing for no warnings double only libraries integration. Ideally a typedef should be used if the code is to be broadly useful, but that's beyond the point.

The `f` is a valid argument - I've had to change `1.0` to `1.0f` when porting from glsl.

I still think it's wasteful using `double`, where `float` is valid, but this is mostly optimization speaking, and I can see where you're coming from with `double`.

**Comment by hollasch** [comment]
Conversion happens in the FPU. Scalar floating point is computed at 64 or 80-bit precision on most architectures. Regardless
- We are not basing this decision on performance
- SIMD and GPU ports are not a goal
- Readers are encouraged to write their own raytracing code

**Comment by hollasch** [comment]
Fixed in #222 (development branch)
