### ISSUE TITLE
`inline` keyword unnecessary

### ISSUE THREAD

**Issue by p1v0t** [RayTracing/raytracing.github.io#153]
From the [cppreference.com](https://en.cppreference.com/w/cpp/language/inline)
> A function defined entirely inside a class/struct/union definition, whether it's a member function or a non-member friend function, is implicitly an inline function.

Some member functions marked as `inline` but it's not necessary as in description.

**Comment by hollasch** [comment]
Interesting note. On Windows, Visual C++ compiler, release build, I moved the `vec3` utility functions out to a separate `vec3.cc` file, and left the header with declarations only. Turns out this hit performance with a 20%–90% slowdown, so the `inline` variants of the functions _outside_ the class are a significant performance boost (again, on the platform I tested). For `vec3` methods, the `inline` keyword is unnecessary, and does not affect performance.

**Comment by hollasch** [comment]
Resolved in #226, changes in development branch.
