### ISSUE TITLE
Many scenes in final code render as black image unless one changes the background color

### ISSUE THREAD

**Issue by ronaldfw** [RayTracing/raytracing.github.io#158]
I just noticed this when playing around with the code. There are several example scenes in the main.cc file that look like one can just uncomment them to render them. But when doing so, one just gets a black image. The reason is that these scenes do not have lights and the background color was set to black (0, 0, 0) at some point (Chapter 6 to be precise). They render fine (assuming good lookfrom / lookat calls) when the background color is set to an actual color.

I think the code is fine as is if it is supposed to represent "here's what you should have at the end of the book", but a couple things we could consider:
- Lighter change: Add comments to indicate that one needs to change background color and lookfrom/lookat calls.
- Heavier change: Background color (and arguably lookfrom/lookat arguments) should be part of the scene.

**Comment by trevordblack** [comment]
Lighter change.

It's industry standard to have the background be an ambient light.

I'm of the opinion that we should either be simple for teaching purposes,
or industry standard.

Following that, we should either simplify, or model the background as a
child of the `light` class.

**Comment by trevordblack** [comment]
I'm going to investigate (and possibly implement) what the changes would look like if we modeled the background as a child of the `light` class

**Comment by hollasch** [comment]
Adding an explicit background color to a `scene` object would be a tidy solution to this issue. See #305.

**Comment by hollasch** [comment]
There's another problem here: the random "world"s that are constructed are distinct from the camera. When you fix the background for these, you often get a view that doesn't make sense for that scene.

I was thinking that the `scene` would be the new `hittable_list`, but now I'm thinking that a `scene` manages the following:

- A background color
- A `hittable_list` of objects
- A camera
- A `sample` function, which takes u,v coordinates and maximum ray depth

Also, the `hittable_list` class should be refactored to use a `std::vector`, with the following methods:

- `clear()` to clear the list of all objects.
- `add()` to add a `hittable*` to the list.

**Comment by mrmcsoftware** [comment]
I probably should have posted this before...  Some code changes I did awhile ago might be of help.  I decoded most of which commented lines go with which scene, and also created a menu to select the desired scene.  Since I don't like ASCII ppm's I also changed it to output binary ppm's.  And since there (most likely) isn't a platform independent way to switch stdout to binary mode, my version creates files rather than having stdout redirected to a file.  Since it was awhile ago, there may have been changes to main.cc that aren't in my version.  Feel free to use any of my changes or even just use it as a reference for decoding the commented code.  I hope the file attachment works right, I've never done it before (on github).  BTW, if you want a menu system, but don't want to switch to binary ppm's, you could send the menu to stderr (changing the code to use stderr) and still redirect stdout on the command line (of course, this would require an OS that treats stdout and stderr differently (Windows and Linux do, don't know about MacOS, but since it's based on Linux/Unix it should)).  Having said all that, it could be that the discussed scene object class might be a better way to go (though it could still use a menu to avoid recompile).

If attachment doesn't work, you can view at: https://drive.google.com/file/d/1ZMlm3xW_uDGnkpdO8aeLF0uq1cfHQWKc/view?usp=sharing

**Comment by mrmcsoftware** [comment]
Opps... line 296 should be:
 if (scene<=5) { nx=1200; ns=10; }

(I changed to a lower resolution in code to render faster, forgot to change 600 back to 1200)

**Comment by hollasch** [comment]
See PR #330
