### ISSUE TITLE
Book 2.5.5: Missing Removal of Code block

### ISSUE THREAD

**Issue by beersandrew** [RayTracing/raytracing.github.io#1660]
In 2.5.1 (Using Blocks of Random Numbers), `perlin.h` is created with a private variable `randfloat`. This variable is removed in 2.5.5 in favor of `randvec`, however the code highlighting for deleting the existing lines with `randfloat` do not appear in the book.

I'm happy to create the PR for this work, but wanted to try to follow the contributing guidelines by posting this issue first to make sure this would be a useful fix.

**Comment by hollasch** [comment]
Sounds great, thanks for catching that. Please go ahead and create a PR against the `dev-patch` branch. Also remember to add a line to the CHANGELOG and add your name to `books/acknowledgments.md.html`.

**Comment by hollasch** [comment]
Reviewing this, I think there's a misunderstanding about highlighted code lines. These do illustrate new/added code, but they also highlight _changed_ lines. So if line A changes to line B, then we only highlight the new line B — we don't also repeat the code that was present before. For pure deletions, we _do_ use deletion highlighting, because there's no other way to communicate that a given line is now removed.
