### ISSUE TITLE
Book 2.5: Missing delete code blocks for noise_texture class

### ISSUE THREAD

**Issue by beersandrew** [RayTracing/raytracing.github.io#1662]
In 2.5.1 (Using Blocks of Random Numbers), the `noise_texture` class is created with a `value` function. This function is subsequently updated throughout the chapter but does not show the deletion of previous value calculations. These updates happen in 2.5.4, 2.5.6, and 2.5.7.

I'm happy to create the PR for this work.

**Comment by hollasch** [comment]
Hi Andrew! Are you the Tableau Andrew Beers?

Regarding our use of delete highlighting, we use this to indicate "naked deletions" rather than "diff deletions", otherwise our listings would be massively larger and harder to read, especially for those readers following along and coding in their own language (and implementation) of choice.

Generally, each listing is an illustration of the code at each step, with highlights to indicate the altered sections, and un-highlighted lines providing context.

**Comment by beersandrew** [comment]
> Hi Andrew! Are you the Tableau Andrew Beers?

Hello! Nope, not me.

> Regarding our use of delete highlighting, we use this to indicate "naked deletions" rather than "diff deletions", otherwise our listings would be massively larger and harder to read, especially for those readers following along and coding in their own language (and implementation) of choice.
> 
> Generally, each listing is an illustration of the code at each step, with highlights to indicate the altered sections, and un-highlighted lines providing context.

Got it, makes sense. Do you want me to close this issue?

**Comment by hollasch** [comment]
I got it — thanks!
