### ISSUE TITLE
Images: Images in books have artifacts

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#179]
Many of the pictures in the html files have obvious signs of artifacts.

There are compression artifacts, maximization artifacts.

Near as I can tell, none of these artifacts produce a wrong-looking or misleading image, but the image quality is occasionally noticeably poor.

**Comment by hollasch** [comment]
Agreed. I've always planned on revisiting the images, but never got around to creating an issue; thanks.

Need to determine desired general image resolution. Some images (like surface acne) might show better as blown-up PNGs.

**Comment by trevordblack** [comment]
We are aware of the problem.
This (#179). #155, and #145 are all probably going to make the next release (2.1.0 or 2.0.1).
We are in no position to merge anything for the next few weeks.

**Comment by hollasch** [comment]
Aras P fixed most of these issues for book1. See PR #230.

**Comment by trevordblack** [comment]
The images should probably be generated at some large texture (e.g. 1000x500, 2000x1000) and some high sample count (e.g. 100+). The src outlined in the book has people printing at lower resolutions and sample counts. Might need to add a slight blurb explaining the increased fidelity.

**Comment by hollasch** [comment]
Current plan for rendered images:

1. Initial PPM image will be 256×256 for easier reading of the output PPM file.
2. General render size to be 384×216, up from 200×100. Still tolerable for performance, easier to view the result. It also yields a 16:9 aspect ratio instead of the previous 2:1.
3. Image parameters now work with an explicit aspect ratio, which drives the vertical resolution. This makes it easier for readers to quickly change the output image size according to their immediate needs.
4. The virtual image window will be computed automatically, without a bunch of hard-coded arithmetic values for various components.

**Comment by hollasch** [comment]
Also note that we want to present actual renders (rather than high-quality ones), so the reader can compare their results against our resulting images.

**Comment by hollasch** [comment]
This has forked out into individual issues.
