### ISSUE TITLE
Implement a formal `scene` object

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#305]
Instead of a static fixed array of object pointers, implement a simple `scene` class that manages the objects in the scene. In addition, this could include scene properties like background color and such.

**Comment by hollasch** [comment]
From #158:

I was thinking that the scene would be the new hittable_list, but now I'm thinking that a scene manages the following:

A background color
A hittable_list of objects
A camera
A sample function, which takes u,v coordinates and maximum ray depth
Also, the hittable_list class should be refactored to use a std::vector, with the following methods:

clear() to clear the list of all objects.
add() to add a hittable* to the list.

**Comment by trevordblack** [comment]
maximum ray depth meaning recursion depth? Not, t_max?

`sample` needs the camera, the list of objects, a `u`, a `v` and a recursion depth.

I don't love putting the `sample` function inside of the `scene` class. I would personally prefer the `scene` to be a bucket of dumb bits, as pure a `struct` as possible.

Do we want to move `time0` and `time1` out of `camera` and into `scene`?
Having the shutter times maintained somewhere with larger scope makes sense to me, but is more work and therefore I don't think is a good idea.

But, this works well for a new user.

**Comment by trevordblack** [comment]
I think the most logical place to introduce these changes in the text is at the start of Chapter 13 [Where Next].

The chapter acts as coda, collecting all of the preceding chapters into one final scene.
It might make sense to actually collect all of the data objects into one class at the same time.

**Comment by trevordblack** [comment]
The final scene in TheNextWeek has a lit up background, and, out of the box, has the wrong colors for the two textured spheres

**Comment by mrmcsoftware** [comment]
I commented in #158 the following, but perhaps it wasn't seen because of #305 superseding? #158.  So, I'll comment here.

-------------

I probably should have posted this before... Some code changes I did awhile ago might be of help. I decoded most of which commented lines go with which scene, and also created a menu to select the desired scene. Since I don't like ASCII ppm's I also changed it to output binary ppm's. And since there (most likely) isn't a platform independent way to switch stdout to binary mode, my version creates files rather than having stdout redirected to a file. Since it was awhile ago, there may have been changes to main.cc that aren't in my version. Feel free to use any of my changes or even just use it as a reference for decoding the commented code. I hope the file attachment works right, I've never done it before (on github). BTW, if you want a menu system, but don't want to switch to binary ppm's, you could send the menu to stderr (changing the code to use stderr) and still redirect stdout on the command line (of course, this would require an OS that treats stdout and stderr differently (Windows and Linux do, don't know about MacOS, but since it's based on Linux/Unix it should)). Having said all that, it could be that the discussed scene object class might be a better way to go (though it could still use a menu to avoid recompile).

If attachment doesn't work, you can view at: https://drive.google.com/file/d/1ZMlm3xW_uDGnkpdO8aeLF0uq1cfHQWKc/view?usp=sharing

-------------

Opps... line 296 should be:
if (scene<=5) { nx=1200; ns=10; }

(I changed to a lower resolution in code to render faster, forgot to change 600 back to 1200)

**Comment by cgyurgyik** [comment]
> From #158:
> 
> I was thinking that the scene would be the new `hittable_list`, but now I'm thinking that a scene manages the following:
> 
> * A background color
> * A `hittable_list` of objects
> * A `camera`
> * A `sample` function, which takes u,v coordinates and maximum ray depth
> 
> Also, the `hittable_list` class should be refactored to use a `std::vector`, with the following methods:
> 
> * `clear()` to clear the list of all objects.
> * `add()` to add a `hittable*` to the list.

Does this still need contributions? This was exactly my thoughts when going through the books.

**Comment by hollasch** [comment]
@cgyurgyik — Yes, we're thinking along the same lines. In the back of my head, I'm thinking of a `renderer` class that has a camera, scene (objects + lights), and rendering parameters. That said, implementing this wouldn't necessarily be any better at teaching the raytracing principles, so I'm still keeping it on the back burner.

**Comment by hollasch** [comment]
See PR #330. In the end, we don't need a formal scene class, particularly because multiple image results are only set in the second book's code. The result is simpler code, and readers are free to create a scene manager of their own design.
