### ISSUE TITLE
suggest: camera param re-order

### ISSUE THREAD

**Issue by dafhi** [RayTracing/raytracing.github.io#404]
Making my way into book 2, am reminded of a camera params restructuring idea I've had since book one:  change the order and progressively assign defaults

Here's what I have
```
class camera {
    public:
        camera(
            double aspect = 4/3,
            vec3 lookfrom = vec3(0,0,0), vec3 lookat = vec3(0,0,-1),
            double aperture = 0, double focus_dist = 1,
            double vfov = 20, // top to bottom, in degrees
            vec3 vup = vec3(0,1,0)
        ) {
```
The How's and Where's in Book One would need attention, I know.

**Comment by hollasch** [comment]
Generally, default values are problematic because they require both the writer and the reader to memorize the full list of arguments, their order, and their implicit default values. This is particularly onerous for a seven-parameter function. In addition, `vup` is the only parameter with a remotely sensible common (> 90% of the use cases) default value.

We will keep the current explicit function signature to make it easier for readers.
