### ISSUE TITLE
Request: Rewrite camera::get_ray to be const

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#446]
Camera::get_ray is a non-const member function.

For multithreading, I would like it be to const, it makes the code more consistent

**Comment by hollasch** [comment]
Probably the correct action here is the surgical fix. Generally, it might be nice to do a `const` method sweep through the code. I'd also like to make all member variables private, and then flip back to public only those members that currently have external access.

However, this is one area where I lean toward cowboy, because I hate the noise and chaff of a bunch of stupid `get`/`set` methods that frequently litter C++ classes. (I do understand why they're used, particularly in professional code, but feel that the price is high. Would love to see better C++ syntactic sugar here. I would also like a pony.)

**Comment by trevordblack** [comment]
It's strange to throw in a request for my own work, but here we are.

**Comment by hollasch** [comment]
When you wish upon a star
Makes no difference who you are
Anything your heart desires will come to you

**Comment by dafhi** [comment]
Does this help?

 "C++ doesn't have this built in, you can define a template to mimic properties functionality:"
https://stackoverflow.com/questions/8368512/does-c11-have-c-style-properties

**Comment by hollasch** [comment]
This approach works for classes that contain a single value only. In addition, our goal is to keep the code as simple as possible, and not use C++ features that a non-C++ programmer would have to learn to understand our sample code.

The C# setter/getter support is really very cool though, and exactly what you'd want: properties that masquerade as member variables, but at any point you can change them to a mock or more complex behavior.

**Comment by dafhi** [comment]
good call on the c++ newbies material; i still don't know how to handle that code.  single value only .. "well that sucks."

thanks for the write-up
