### ISSUE TITLE
Add Bibtex citations

### ISSUE THREAD

**Issue by Yordrar** [RayTracing/raytracing.github.io#500]
There should be an official bibtex citation in the website so that the books can be consistently cited by everyone. 

This issue is the result of this Twitter thread: https://twitter.com/hollasch/status/1255950344489537537.

There are some suggestions in said thread, although the different interpretations are worth discussing.

**Comment by hollasch** [comment]
From the thread above:

IEEE: `“Ray Tracing in One Weekend Series.” raytracing.github.io (accessed Apr. 30, 2020).`

MLA: `Ray Tracing in One Weekend Series. raytracing.github.io. Accessed 30 Apr. 2020.`

BibTex: `@misc{shirley, title={Ray Tracing in One Weekend-The Book Series}, url={raytracing.github.io}, journal={Ray Tracing in One Weekend Series}, author={Shirley, Peter}}`

`@book{raytracing_weekend, title = {Ray Tracing in One Weekend}, author = {Peter Shirley}, year = {2020}, edition = {3.0.2}, url = {raytracing.github.io/books/RayTracingInOneWeekend.html}}`

I don't know if it makes sense to to include every possible citation format, because if someone needs it, they'll need it to match whatever style they're citing for. Perhaps it might be better to just ensure that all possible bibliographic information is available up front.

Here's a list of possible pieces of information, along with examples:

- **Title (series):** “Ray Tracing in One Weekend Series”
- **Title (book):** “Ray Tracing: The Rest of Your Life”
- **Author:** Peter Shirley
- **Editors:** Steve Hollasch, Trevor David Black
- **Version/Edition:** v3.1.0
- **Date:** 2020-05-03
- **URL (series):** https://raytracing.github.io/
- **URL (book):** https://raytracing.github.io/books/RayTracingInOneWeekend.html

Perhaps the only change we need to make is to ensure that the URL is included in the front blob, change from “Version” to “Edition”, and put the date on a separate line. Something like this:

```
                           Ray Tracing in One Weekend
                                by Peter Shirley
                edited by Steve Hollasch and Trevor David Black

                                 Edition v3.1.0
                                   2020-05-03

         https://raytracing.github.io/books/RayTracingInOneWeekend.html

                     The Ray Tracing in One Weekend Series
                         https://raytracing.github.io/

            Copyright 2018-2020 Peter Shirley. All rights reserved.
```

**Comment by trevordblack** [comment]
I think the sane thing here is more data, Morgan Mcguire's approach for his graphics archive:

https://casual-effects.com/g3d/data10/index.html

I wish that there was ONE BIB TO RULE THEM. But IEEE and MLA haven't yet had the bibliography thunderdome that the world sorely needs. And so, in this, the year of lord, 2020, we still haven't managed to standardize this, I think the best thing to do is to just do all of them. ::sigh::

**Comment by hollasch** [comment]
Oh good grief. We're going to have to update this _every time we release a new version_. The horror.

I like the idea of updating the front blob above, but I also think following Morgan's example above is an excellent suggestion. Section before Acknowledgments? Each book should get updated. Tempting to script this somehow.

**Comment by Yordrar** [comment]
My proposal was based on McGuire's Graphics Codex and I like it because it explicitly states the book version, and thus anyone can go to the specific version in case the books change substantially. However I understand that it's a big pain updating the version of each book (therefore 3 citations) each time and the set-and-forget, one-citation style of citing the entire series as a whole might be more sane for the editors.

That said, if it's possible to script it like @hollasch said, citing the three books separately might be feasible.
