### ISSUE TITLE
Ray Tracing In One Weekend : Missing cosine component for diffuse materials ?

### ISSUE THREAD

**Issue by almathie** [RayTracing/raytracing.github.io#543]
I am quite new to ray tracing so, please excuse me if I made a mistake here.

My Issue resides with this line:
https://github.com/RayTracing/raytracing.github.io/blob/master/books/RayTracingInOneWeekend.html#L1800

In the current version of the book, this is figure 40 on chapter 8.6

In this chapter, the author proposes a better version for the diffuse material.
The idea is to cast a new ray from the intersection point onto a half sphere centered at the intersection point and oriented according to the normal.

Now the illumination equation is this:

![image](https://user-images.githubusercontent.com/1334730/82106364-b6cf2d80-9720-11ea-96e1-f1323ce23192.png)

From what I understand for that code, for a perfectly diffuse material, we have : 

- The emitted light (orange component) is 0.
- The fact that we need to integrate over the hemisphere (light blue part) is given by the fact that cast many many rays per pixels.
- The probability of the incoming light hitting (pink component) is provided by the fact we casted a random ray on the hemisphere - For a metallic object we should change this.
- The color of the incoming light (purple component) is provided by the fact that we compute the color of the incoming ray, then multiply it by 0.5, to produce a light gray object.

But where is that code is the irradiance factor (green part) taken into account ?
From my understanding, if we assume that the normal is expressed as a unit vectors, we need to multiply the color by the cosine.

As far as I can see, the code was taken from this snippet:

https://github.com/RayTracing/raytracing.github.io/blob/master/books/RayTracingInOneWeekend.html#L1527

But in this version, the cosine is not needed because the way the rays are chosen itself is tweaked so that there will less rays cast at low angles so on average it will even out.

**Comment by trevordblack** [comment]
If my understanding of your question is right, then I believe that you are correct.

We're approximating the cosine by selecting a point on the surface of unit sphere. We're not integrating over the whole unit sphere because that would either require an analytic solution (which we don't have) or infinite time. Instead, we're approximating the cosine term by summing a bunch of samples that have been chosen with a cosine distribution.


The original text used an algorithm that produced a cosine cubed (cos^3) distribution there.
The "naive" approach of just sampling the hemisphere will produce a uniform distribution (a 1 term there), so no green part.

Do I understand your question correctly?
You're right that the illumination equation isn't directly addressed in book 1, but that's because it makes more sense as a book 3 entry, and won't be added because it's more friction than we'd like in the first book.

It's really cool that you're trying to marry all of the ideas in the first book to more advanced concepts, like the illumination equation. There are a lot more advanced concepts in the later books.

Did that answer your question?

**Comment by trevordblack** [comment]
Closing out this issue
