### ISSUE TITLE
Book 3, Section 6.1: Uses random_in_unit_sphere?

### ISSUE THREAD

**Issue by pgetto** [RayTracing/raytracing.github.io#617]
The "Cornell box, refactored" image seems to be based on an older version of the Lambertian scatter() function which uses the random_in_unit_sphere function to generate the direction for the scatter ray. 

The version of scatter() which uses random_unit_vector (as in the code at the end of Book 2), generates the "same" image as the "Cornell box, with different sampling strategy" image.

So, the conclusion of section 6.2 in book 3 is a little confusing. I expect most will be using the random_unit_vector() function and will see the "same" image after the changes to prepare for importance sampling.

**Comment by hollasch** [comment]
We have a large task (almost completed for book 1) of updating every render with the latest changes. There are many differences. Book 1 images are targeted for v3.2.0, while books 2 & 3 may or may not make it into that release.

**Comment by pgetto** [comment]
Thanks for your reply. This is about the text as much as the image (I think).

But, if you need help generating some of the images, I would be happy to help. I am mid-way through book 3 (though I have done my implementation in Java, so it is not exactly the same code).

**Comment by hollasch** [comment]
Ah, sorry, I thought you were talking about image differences. I understand now.

**Comment by trevordblack** [comment]
I was aware of the Cornell Box problem in section 6.2 and 6.3, where the Lambertian rewrites would confuse the Cornell Box commentary because we moved to the new `random_unit_vector`

I could have sworn I documented that somewhere, but I've lost the issue.

You're correct. Moving to the "correct" lambertian in book 1 means a lot of the text in book 3 will be confused. Section 6.2 and 6.3 is a journey that starts at  "incorrect" lambertian and ends at "correct" lambertian. Now, starting with "correct" lambertian definitely muddies the text.

This will require some small (but VERY significant) rewrites. This likely isn't going to make into 3.2.0

**Comment by pgetto** [comment]
Yes, exactly.

**Comment by trevordblack** [comment]
I believe this was resolved in #832

@pgetto Do you agree?
These changes are already in the dev-major branch if you're interested or willing to checkout that branch and then open `books/RayTracingTheRestOfYourLife.html` in a browser

**Comment by trevordblack** [comment]
Closing this out.
