### ISSUE TITLE
[The Rest of Your Life]Mixture pdf with Metal have bright noise point

### ISSUE THREAD

**Issue by huang-jl** [RayTracing/raytracing.github.io#637]
Following the book(The Rest of Your Life) in Chapter 10 Cleaning Up pdf Management, we are going to support specular light. However, when rendering cornell box with a metal material, the result is different from the picture in books.   

There are a lot of **bright point** near the metal box and the light, which looks like powder. I notice the picture on book only have a **slightly bright** area there.  
   
*I wonder where might cause that problem?* Thanks a lot. 

![image](https://user-images.githubusercontent.com/49710099/84587943-f7bc7e00-ae55-11ea-9e90-cf1334ecc4b8.png)

**Comment by trevordblack** [comment]
Those look like Fireflies.

They are caused by a ray bouncing off a surface and intersecting with a light. The pixel right next to that one might not bounce into the light. So you get one really bright pixel next to one normal brightness pixel.

There are a lot of ways to get rid of fireflies, that are described in various literature. Unfortunately, all of these techniques are well beyond the scope of these books.

If the problem is just fireflies (and it looks like it is). Try increasing the sampling rate. What's your current sample rate?

**Comment by huang-jl** [comment]
I only run it to test the correctness for my code, so using a low sample rate. Three days passed, what I remember is 100 samples per pixel at most.

**Comment by trevordblack** [comment]
I'm going to close out this issue. They look like fireflies. It's probable that rendering the images of book 3 will dial in an appropriate amount of spp.
