### ISSUE TITLE
Addition of time in "moving_sphere" chapter not explicitly added to all material types

### ISSUE THREAD

**Issue by trevordblack** [RayTracing/raytracing.github.io#654]
Chapter 2.4 outlines how to add time to the rays created from a lambertian material. But we do not have explicitly have the code for diffuse or metal materials. This is probably unnecessary as ray.h does not have a constructor that lacks time. So it'll come up as a compile error, and the user will hopefully realize the additions needed.

However, the source at `src/Common/ray.h` has two constructors:
```
ray(const point3& origin, const vec3& direction)
ray(const point3& origin, const vec3& direction, double time)
```

So someone using the ray.h from the github source might be accidentally setting all of their diffuse, metal ray intersections to time = 0

**Comment by Walther** [comment]
This might be slightly controversial, feel free to take this with a grain of salt, and I hope this doesn't come off as too harsh!

What is the added value of having the moving sphere? The added complexities are that a reader now has to make every single function in the call chain pass time values, especially if following this tutorial in a language that is stricter, or using abstractions over the objects and materials. The reader may also need to adapt various functions from the book on the fly to account for the time parameter that is missing here and there. Additionally, as the moving versions of other objects are not provided, the reader has to implement those on their own, or add special handling for assuming a fixed time in those methods, or use some other approach. This creates some extra friction for the reader that slows down following the actual content of incrementally building a better raytracer.

**Comment by hollasch** [comment]
This is a tough one. I don't know why @petershirley originally included this in the book, but I can offer my opinion.

For me, this goes back to Robert Cook's paper on stochastic sampling (https://graphics.pixar.com/library/StochasticSampling/paper.pdf). The really wonderful idea here was that rays could be sampled not just in space, but also in time, or aperture, or color, or over any other involved continuous domain you can think of. For example, we could implement prismatic refraction by adding a wavelength to the scene rays. I like the inclusion of this effect because motion blur is a feature that people commonly want, but more than that, because it suggests how one might widen their thinking about using rays to sample a scene.

I do agree that it comes at a price, particularly since it burdens every ray interaction with a time value. It's quite possible that instead of having all rays be equivalent, a simpler implementation might use subclassing to be more clear about when timed rays are used, and when regular rays are used. This would hopefully let simple classes remain simple, at the cost of increasing the size of a ray by 16 or more bytes.

This is the kind of thing we're still wrestling with — how to introduce related interesting raytracing topics. So far we've kicked around using appendices, adding more books to the series, adding "papers" or "supplements" to books that subsequent books don't rely on, or just creating new projects to go deep into other variants. In the end, there's no obvious easy solution. It's quite possible that the better approach here is to migrate time-based sampling to a dead-end project or book, and then abandon it as the series continues.

**Comment by Walther** [comment]
Thank you for the thoughtful response! The expansion of thinking is _definitely_ a high-value aspect, and probably shouldn't get cut after all. Didn't occur to me that without that example, I probably wouldn't have even thought about the possibility of rays existing in variable time and giving interesting results in aggregate.

Random thought: maybe something like adding the moving spheres early in the books (as they currently are), explicitly mentioning the opportunities and perspective-widening, and then maybe saying the rest of the series will revert to non-moving objects? 🤔 Or something else entirely, I don't know.

**Comment by petershirley** [comment]
I don't know why I added it either :)    I know something I have run into before is that when you need to add the time feature later in a ray tracer it touches a *ton* of the calls.    Given that some other things that will certainly need to be added to people's systems that we don't discuss (shadow rays being the biggest?) time seems questionable.  I'll think about this more, but I don't object to ditching it.  My main misgiving is that brute force works so well here you get an advanced effect for little cost.  Steve's point about wavelength is spot on.  Migration someplace followed by abandonment has an appeal....

**Comment by trevordblack** [comment]
Not to dogpile you here...

This is something that I've thought about, _a lot_, actually. See this and #408 for the most public example.

I tend to think of these things in terms of axioms, where we can discuss each's merit:
1. The books should include the temporal dimension
2. It should be covered before the end of book 2
3. It needs an example
4. The books should be as frictionless as possible

When I brought up #408 (where we would move the BVH chapter to chapter 1, and shift moving_spheres further along book 2), the reason I closed out that issue is because the BVH chapter is ***dry***. Starting a new adventure (book 2!) with that chapter would grind any enthusiasm to a halt.

If nothing else, were we to remove the moving_spheres chapter, I would strongly recommend putting something else ahead of BVH. The problem with that is, though, that BVH touches almost everything. So you have two chapters (bvh and moving_spheres) where each impacts a massive part of the codebase.

> The really wonderful idea here was that rays could be sampled not just in space, but also in time, or aperture, or color, or over any other involved continuous domain you can think of.
> It's quite possible that instead of having all rays be equivalent, a simpler implementation might use subclassing to be more clear about when timed rays are used, and when regular rays are used.

The latter would definitely muddy the former. If we're building an intuition about different dimensions of sampling (which, are we? That was never my impression), having specific objects that are outside certain dimensions is definitely a more complicated mental model.

I'm open to the idea of shifting moving_spheres to book 1. That might actually be a worthwhile tradeoff.
It's more work for the reader, but if we're really gunning for the idea of broadening the reader's horizons, that's really more of book 1's bag than book 2.

I could see the temporal dimension and moving_spheres also working well if we pushed it back to book 3. Maybe in book 3 we could add a chapter on importance sampling over the temporal dimension. That might actually help congeal a lot of things at once....

The biggest systems (that touch a lot of other systems) that we don't cover (in no particular order):
- Multithreading
- Affine Transforms
- Triangles
- Shadow Rays
