### ISSUE TITLE
checker_texture is spatially defined, could or should be defined by surface coordinates (U,V)

### ISSUE THREAD

**Issue by ChenNingCong** [RayTracing/raytracing.github.io#663]
Maybe this is an intended behavior.
The checked texture didn't use uv coordinate at all...it just use the normal (which is parameter p) at the hit point. This get correct result in final scene, but the image of  "Checkered spheres" is weird.
```C++
 virtual color value(double u, double v, const point3& p) const {
            auto sines = sin(10*p.x())*sin(10*p.y())*sin(10*p.z());
            if (sines < 0)
                return odd->value(u, v, p);
            else
                return even->value(u, v, p);
        }
```
If we use u,v in place of `p.x() p.y()`, we can get the following image:
![twosphere](https://user-images.githubusercontent.com/42328994/87169421-f8520400-c29d-11ea-8070-477c05b0a983.png)
(But this will cause the texture in final scene weird)

**Comment by hollasch** [comment]
Possibly related: #533, #534

**Comment by Walther** [comment]
The example image in this issue looks intuitively more correct for a checkered sphere - looks similar to e.g. the famous Amiga sphere.

Comparing to the example in the book:
![checkered spheres](https://raytracing.github.io/images/img-2.03-checker-spheres.png)

This implementation has weird stripes that messes up the checker pattern. Larger render from my implementation for more detail:
![1593274379](https://user-images.githubusercontent.com/2943750/96581986-5487e380-12e3-11eb-9cd6-e9eb863241d0.png)

Of course, any fixes for this would need to also take into account the image texture mapping as mentioned in #533 and #534 - to not break that one instead.

**Comment by hollasch** [comment]
We _could_ introduce the concept of spatial vs surface texturing, yielding `checker_texture` and `spatial_checker_texture`, or `checker_texture` with a constructor parameter or something that indicates whether it responds to surface coordinates or spatial position. Both are useful, so it would be good to introduce this concept, particularly with this kind of texture.

**Comment by hollasch** [comment]
A thought — why not both? The texture as currently implemented is a great simple example of spatial textures. Even better, it's useful to illustrate a common bug in surface textures. We could either implement `spatial_checker` and a `surface_checker` classes, or implement spatial first, talk about the behavior, and then add a constructor value or a setter that allows it to work either in spatial or surface mode.

**Comment by trevordblack** [comment]
I think both is fine.

The checker_texture as is is really more of a 3dimensional version of the 2d surface texture

**Comment by petershirley** [comment]
I think both would be fine.  The 3D vs 2D texture concept is so important, bringing it up makes sense when in doubt?

**Comment by hollasch** [comment]
Reflecting on this, the image texture is a great example of texturing via surface coordinates. I think that we should leave checker as a spatial texture, particularly since it immediately follows the image map. However, there's an important leap from surface to spatial that really isn't mentioned or explained in the text. I think the proper fix here is to talk a bit about this distinction when introducing the checker texture.

**Comment by Walther** [comment]
Two random sidenotes from a reader:

Sidenote 1: I think both would be fine - introducing the concept of spatial textures is great for giving people ideas about possibilities, and a surface-defined checker texture would be [quite a classic](https://en.wikipedia.org/wiki/Amiga#/media/File:Boingball.png).

Sidenote 2: the current implementation behaves poorly on a flat, axis-aligned surface at 0.0 - because everything goes to zero, it returns a single color for the entire plane. Wonder if there's a way to make this well-behaved through zero, other than leveraging the epsilon...

**Comment by hollasch** [comment]
Regarding sidenote 1: the current text doesn't really point out the difference between a spatial coordinate scheme and a surface coordinate scheme. I certainly think that it makes sense to point out that a checker texture is a useful exercise for the reader, and leave it at that.

For sidenote 2, that's an excellent point. I hadn't really looked at the implementation myself, but that's certainly a flaw. I'd be very tempted instead to cast each dimension to an integer, and then XOR the modulo-2 of each dimension to get either the first or second texture. Or something like that, as I'm just pulling this off the top of my head. An additional thing to consider when ultimately addressing this.
