### ISSUE TITLE
std::clamp

### ISSUE THREAD

**Issue by define-private-public** [RayTracing/raytracing.github.io#683]
I'm going through the first book right now (again) and there's a part where we implement a `clamp()` function.  In C++17, they added a `std::clamp()` function itself.

https://en.cppreference.com/w/cpp/algorithm/clamp

I'm not sure if there's any benefit to using that one than the one that's implemented in the book. On another side note, `clamp()` can also be implemented using the `min()`/`max()` functions:

`std::max(std::min(n, max_value), min_value)`

Once again, I'm not sure if there is any performance benefit, but it does look a bit cleaner than having those conditionals.

**Comment by hollasch** [comment]
We decided to manually define a clamping function in order to keep to a maximum of C++11, and only required pieces at that (like `shared_ptr`).

`std::clamp` also technically doesn't support NaN values, and ray tracing is a NaN-producing factory. (Also note that the fact that `std::min` and `std::max` _do_ provide specific NaN behavior is why they're much more expensive than a simple statement with ternary operators.)

**Comment by hollasch** [comment]
Of course, the provided code is an _example_ implementation only. You should definitely implement your own ray tracer in the style you choose. Personally, I'd use the latest & greatest C++ everywhere, as a way to dive into new features as well.
