### ISSUE TITLE
[Suggestion] [Book 2] Improve the perlin texture example

### ISSUE THREAD

**Issue by rongguodong** [RayTracing/raytracing.github.io#716]
The current version uses two spheres with perlin texture. As the result, each sphere's own texture is blended with the reflected color from the other sphere. The result is quite difficult to understand.

I tried to change the small sphere with a metal texture. I think the result is much easier for readers to understand. The following is the image I got for "Image 7" for your reference:
![image](https://user-images.githubusercontent.com/11858549/91494978-9d389880-e86e-11ea-8074-a3d675e80285.png)
This is generated with the following line:
![image](https://user-images.githubusercontent.com/11858549/91495003-ac1f4b00-e86e-11ea-8d80-cc47cffcb8c0.png)

**Comment by hollasch** [comment]
While the rendered textures do show some small amount of shading, and an even smaller of amount of reflected texture shading, the ground shows the results of applying Perlin to a mostly flat surface, while the sphere does a good job at showing the 3D nature of the underling Perlin texture space that would be otherwise hidden. I think we'll keep the scene as it is.
