### ISSUE TITLE
[Suggestion] Make a branch for each chapter

### ISSUE THREAD

**Issue by rongguodong** [RayTracing/raytracing.github.io#717]
Although we expect readers to gradually update the code after each chapter, it is hard to recover the code to a certain chapter, and we only have the "current version". If I have finished a book and want to get a version of code when I finished Chapter X, it is very hard to do that.

If we can have a branch for each chapter, it would be easy to use "git checkout" to get any version we want.

**Comment by hollasch** [comment]
No.
No no no no no no.
:D

We already have to propagate changes from earlier points in the exposition through through all development phases, which is a huge headache. In fact, in order to do our recent all-books image updates, we did exactly what you proposed. That code lasted about one month before it was hopelessly out of date again, so we had to discard those branches (multiple times). _At best_, it means rebasing the entire branch after every single change. In most cases, changes happen in the middle of development, so you need to cherry-pick into the middle of the progression branch, then rebase while squashing the cherry-pick in with the progression commits.

The value of this is also diminished because readers are strongly encouraged to write their own code, while using the book's code as a passing reference.

Interestingly, this whole problem caused me to realize that what is needed is a system and toolset for what I've been calling "multi-dimensional version control". For example, consider what would happen if we published an additional RTW in Rust. And one using Python. And a German edition. These are all "timelines" that have a formal relationship, but no system/toolset that I know of today offers a solution, or even nomenclature for such a problem space. There's a paper in here, but I'll probably never get to writing it.

But the short answer is that both Trevor and I have numerous cuts and bruises from building this structure, after which we had to burn it to the ground. After the pain of maintaining this for just a couple of weeks, deleting these progression branches is particularly cathartic.

Sorry. :}
