### ISSUE TITLE
Add navigation bar to each book's page

### ISSUE THREAD

**Issue by JC-ProgJava** [RayTracing/raytracing.github.io#827]
Hi! I had a great time reading your ray tracing series, but have one suggestion: would it be possible if a navigation bar was added to each of the book pages that link to the main page and the other book's pages? This would greatly enhance navigation between the books, thanks!

**Comment by hollasch** [comment]
I'm afraid that this would be difficult, because each book stands on its own. This is particularly important because it's tightly coupled with the source code, and readers should be insulated from the thrash of ongoing updates and changes. In fact, it might make sense that a reader does v2.1.0 of book 1, then sets it aside, grabs v3.0.0 for book 2. We _do_ launch to the latest released version of each book from the web site, but that's just a springboard for readers who want to browse the latest version.

Maintaining cross-book cohesion while all three (and subsequent) books change sounds like more work than we could handle at the moment.

Still, a good idea to think about additional navigational aids, so I'm tossing this on the backlog for future consideration.

**Comment by hollasch** [comment]
Hmm, I thought it could be useful to have a table of contents presented in a left pane, but it doesn't look like Markdeep supports this. I'll keep an eye on new Markdeep future releases with this in mind, but for now there's nothing really for us to do.
