### ISSUE TITLE
rotate_y resulting in weird shadows

### ISSUE THREAD

**Issue by wendelscardua** [RayTracing/raytracing.github.io#845]
I've been following the books and implementing the algorithms in Crystal, but when rendering some custom scenes (like an sphere with earthmap texture, rotated 75 degrees) there was a dark shadow on the sphere. At first I thought it was a bug on my code, but just now I've reproduced the issue using the reference C++ implementation, running "theNextWeek" with these alternative scenes:

1.  `two_spheres`, but changing the second one to be rotated:
```
    objects.add(make_shared<sphere>(point3(0,-10, 0), 10, make_shared<lambertian>(checker)));
    objects.add(make_shared<rotate_y>(make_shared<sphere>(point3(0, 10, 0), 10, make_shared<lambertian>(checker)), 75));
```

2. `earth`, also changing the sphere to be rotated:
```
    auto globe = make_shared<sphere>(point3(0,0,0), 2, earth_surface);
    auto rot_globe = make_shared<rotate_y>(globe, 75);
    return hittable_list(rot_globe);
```
See the resulting images below:

![two-spheres](https://user-images.githubusercontent.com/3289356/103442271-7088f900-4c33-11eb-8834-489a92d7d150.png)
![earth](https://user-images.githubusercontent.com/3289356/103442268-6b2bae80-4c33-11eb-96de-f28c9bbac2ea.png)

**Comment by ocirne** [comment]
Found a work-around. In "Pseudocode": In rotate_y::hit instead of 
```
        val frontFace = r.direction.dot(outward_normal) < 0
        val normal = if (frontFace) outward_normal else -outward_normal
```
simply do
```
        val normal = outward_normal
```
front_face matters only for materials dielectric and diffuseLight. But I guess there are textures unlikely.

Why? My (probably wrong) assumption is, that the surface normal was already rotated, so that another correction is wrong.

**Comment by trevordblack** [comment]
Near as I can tell, this issue is a subset of #544

**Comment by wendelscardua** [comment]
@trevordblack but #544 seems to be focused on the rotation logic being "correct" and lacking more explanation, and #662 seems to be about quadrilaterals and Book 3 issues, while this is an issue with spheres on Book 2. Maybe the three of them are a subset of "Rotations need some rework" if that issue existed here.

**Comment by trevordblack** [comment]
Okay. Following up on this.

I'm now 99% sure that this is the sibling problem that #889 found.

The problem there was the rotation and translation code was incorrectly reassigning the normals.
The commit for that issue is https://github.com/RayTracing/raytracing.github.io/commit/e17e01df3c0c064b6b88f3b8b61ab977ef2f97c4

currently in PR #913 

I can successfully reproduce the bug under both the two spheres and earth outlined above, thank you for that.

When I reproduce with the commit above, the error goes away. It makes sense that this is a normal issue. So, if you want,
you can try to reproduce the bug with the commit outlined above, but if not, I'm going to go ahead and close out this bug
after the PR successfully lands.

Thank you

**Comment by trevordblack** [comment]
@ocirne's assessment above is correct.

**Comment by trevordblack** [comment]
Closing as PR landed
