### ISSUE TITLE
Book 1: Section 9.3 problems with the rec variable

### ISSUE THREAD

**Issue by robinjo78** [RayTracing/raytracing.github.io#878]
Hi,

When implementing the lambertian class in section 9.3 I get problems with using the rec variable. It raises the error: "incomplete type is not allowed" when calling the normal and p attribute on the rec variable. I couldn't find any fix on Google. What could be the problem?

Below the code with the error lines indicated:

`
class lambertian : public material {
public:
	lambertian(const color& a) : albedo(a) {}

	virtual bool scatter(
		const ray& r_in, const hit_record& rec, color& attenuation, ray& scattered
	) const override {
		auto scatter_direction = rec.normal + random_unit_vector();  //line with the error.

		// Catch degenerate scatter direction
		if (scatter_direction.near_zero())
			scatter_direction = rec.normal;     //line with the error.

		scattered = ray(rec.p, scatter_direction);      //line with the error.
		attenuation = albedo;
		return true;
	}

public:
	color albedo;
};
`

**Comment by ayyaraashish** [comment]
Include hittable.h after rtweekend.h.

**Comment by trevordblack** [comment]
Hang on, confirming a fix,

did you not have
```
#include "hittable_list.h"
```
within your main.h?

Or did you swap the order of the includes?
you had:
```
#include "material.h"
#include "hittable_list.h"
```
when you should have had:
```
#include "hittable_list.h"
#include "material.h"
```

I can't really think of a reason that you would otherwise run into this problem?


Regardless, listing 50 (now listing 55 in `dev-major`) needs more context lines on either side
```
...

#include "material.h"

...
```

So, wonderful! Thank you for that catch!

**Comment by trevordblack** [comment]
Closing this out.
