### ISSUE TITLE
Book 1 Section 4.2 (4.8) Image-Coordinates vs U-V-Coordinates

### ISSUE THREAD

**Issue by NiklasVousten** [RayTracing/raytracing.github.io#879]
The Ray for calculating the Color is generated by using u-,v-Coordinates wich are derived from the x-,y-Coordinates from the Image. This means the Color is the same for every given x-,y-Coordinate no matter the order.
But the Order matters for the PPM Format and (0,0) is the upper left corner.
The generation of the image start the y-loop at IMAGE_HEIGHT and every pixel written to the image is flipped.
When using an image-library wich has a put_pixel(x,y,c) function the order wont matter.

Changing the return of ray_color to fix the issue:
t*color(1.0, 1.0, 1.0) + (1-t)*color(0.5, 0.7, 1.0)

The y-loop must now start at 0 to keep the PPM Format working

**Comment by hollasch** [comment]
Are you referring to an old version of the book? There are only two sections in chapter four: https://raytracing.github.io/books/RayTracingInOneWeekend.html

**Comment by NiklasVousten** [comment]
Sorry. I mean Section 4.2. Is 4.8 in the Text as a headline

**Comment by NiklasVousten** [comment]
Figured out this will create a later problem, because know the whole Coordinate system is fliped. So the v-Coordinate is the opposite of the y-Coordinate in 3D-Space

**Comment by NiklasVousten** [comment]
Code is correct. Sorry for bothering you.
Fix is to change the part for the Image-Format, so that the y, which creates the v-Coordinate is a different y in the Image-Space.
y_img = (IMAGE_HEIGHT - 1) - y_loop

This doesnt really matter for the PPM Format, because you only have to loop in the right order.

Maybe adding a notice in a future Version to keep the Image-Coordinate in mind which has (0,0) in top Left Corner and is different from u-v-Space

**Comment by hollasch** [comment]
Thanks for following up. You're correct that flipping V just pushes the transform down further in the spatial pipeline — you'll pay the price somewhere.

If you want to always think of images as having an inverted Y-axis, it would make sense to change the i, j loop indices so that j starts at zero, like so:

```
auto imax = image_width - 1;
auto jmax = image_height - 1;

for (int j=0; j <= jmax; ++j) {
    for (int i=0; i <= imax; ++i) {
        auto u = double(i) / imax;
        auto v = double(jmax - j) / jmax; // Handle inverted image Y coordinate
        ...
    }
}
```

I have to update this specific code for other reasons; I may incorporate this approach as well.

As always, the idea is for you to write the code that makes sense to you — feel free to implement this with your own style and approaches. Experimentation is the whole idea of the book! :)

**Comment by hollasch** [comment]
So our basic code is correct. However, we will be updating our camera code, and will likely adopt the looping approach outlined in my last message.

See #1041, #1042
