### ISSUE TITLE
Render bug with lambertian material leads to only the light being displayed in book 3

### ISSUE THREAD

**Issue by AnonymousAAArdvark** [RayTracing/raytracing.github.io#882]
I have just finished implementing book 3 and I am trying to edit the objects within the box. 

All of my hittables render correctly with dieletric and metal materials, however adding any non-specular material causes the program to only render the light. What confuses me the most is that when I use the example renders the program works fine, and so that led to believe that there is some bug in my code. This is not the case, since the bug persists when I compile the source code. Attached below is an image of a faulty render.

![image](https://user-images.githubusercontent.com/42499336/114292033-a44c9980-9a40-11eb-9652-8a7fa0a91d89.png)

**Comment by hollasch** [comment]
Are you using the latest release (v3.2.3)? I'd be curious to know if the same problem persists with the v4.0.0 code currently under development in the dev-major branch. It's a big change though, so not really asking you to switch (particularly since development is ongoing).

We will be do another full code run through all three books to validate the changes and possibly update rendered images, so will hopefully also get some validation there. However, the bug may still persist for non-specular materials. We'll give those a shot while doing the run-through.

**Comment by AnonymousAAArdvark** [comment]
Hmm... it looks like the bug has been fixed in the 4.0.0 version! I'm sorry for bothering you, I should've looked into the dev branch before posting an issue.

**Comment by hollasch** [comment]
Ha, following along with the development branch is a recipe for headaches and rage. :) I mean, you _could_, but that would be going above and beyond.

So, thank you very much for confirming a fix!
